version: '3'

services:
  url-frontier:
    build:
      context: url-frontier
      dockerfile: url-frontier.dockerfile
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      - DATABASE_URL=postgres://postgres@localhost:5432/urlfrontier
      - RABBITMQ_URL=amqp://guest:guest@localhost:5672
    network_mode: host